// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
@ffi.DefaultAsset('package:frostdart/frostdart_bindings_generated.dart')
library;

import 'dart:ffi' as ffi;

@ffi.Native<
  CResult_OwnedString Function(
    ffi.UnsignedInt,
    ffi.Pointer<ThresholdKeysWrapper>,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Bool,
    ffi.Bool,
  )
>()
external CResult_OwnedString address_for_keys(
  int network,
  ffi.Pointer<ThresholdKeysWrapper> keys,
  int account,
  int address,
  bool change,
  bool secure,
);

@ffi.Native<
  CResult_AttemptSignRes Function(
    ffi.Pointer<ThresholdKeysWrapper>,
    ffi.Pointer<SignConfig>,
  )
>()
external CResult_AttemptSignRes attempt_sign(
  ffi.Pointer<ThresholdKeysWrapper> keys,
  ffi.Pointer<SignConfig> config,
);

@ffi.Native<
  CResult_KeyGenRes Function(
    ffi.Pointer<MultisigConfigWithName>,
    SecretSharesRes,
    ffi.Pointer<StringView>,
    ffi.UintPtr,
  )
>()
external CResult_KeyGenRes complete_key_gen(
  ffi.Pointer<MultisigConfigWithName> config,
  SecretSharesRes machine_and_commitments,
  ffi.Pointer<StringView> shares,
  int shares_len,
);

@ffi.Native<
  CResult_ResharedRes Function(StartResharedRes, ffi.Pointer<StringView>)
>()
external CResult_ResharedRes complete_reshared(
  StartResharedRes prior,
  ffi.Pointer<StringView> resharer_completes,
);

@ffi.Native<
  CResult_OwnedString Function(StartResharerRes, ffi.Pointer<StringView>)
>()
external CResult_OwnedString complete_resharer(
  StartResharerRes machine,
  ffi.Pointer<StringView> encryption_keys_of_reshared_to,
);

@ffi.Native<
  CResult_OwnedString Function(
    ffi.Pointer<TransactionSignatureMachineWrapper>,
    ffi.Pointer<StringView>,
    ffi.UintPtr,
  )
>()
external CResult_OwnedString complete_sign(
  ffi.Pointer<TransactionSignatureMachineWrapper> machine,
  ffi.Pointer<StringView> shares,
  int shares_len,
);

@ffi.Native<
  CResult_ContinueSignRes Function(
    ffi.Pointer<TransactionSignMachineWrapper>,
    ffi.Pointer<StringView>,
    ffi.UintPtr,
  )
>()
external CResult_ContinueSignRes continue_sign(
  ffi.Pointer<TransactionSignMachineWrapper> machine,
  ffi.Pointer<StringView> preprocesses,
  int preprocesses_len,
);

@ffi.Native<CResult_MultisigConfig Function(StringView)>()
external CResult_MultisigConfig decode_multisig_config(StringView config);

@ffi.Native<CResult_ResharerConfig Function(StringView)>()
external CResult_ResharerConfig decode_resharer_config(StringView config);

@ffi.Native<
  CResult_SignConfig Function(
    ffi.Pointer<ThresholdKeysWrapper>,
    ffi.UnsignedInt,
    StringView,
  )
>()
external CResult_SignConfig decode_sign_config(
  ffi.Pointer<ThresholdKeysWrapper> keys,
  int network,
  StringView encoded,
);

@ffi.Native<CResult_ThresholdKeysWrapper Function(StringView)>()
external CResult_ThresholdKeysWrapper deserialize_keys(StringView keys);

@ffi.Native<OwnedString Function(ffi.Pointer<MultisigConfig>)>()
external OwnedString encode_multisig_config(ffi.Pointer<MultisigConfig> self);

@ffi.Native<ffi.Void Function(OwnedString)>()
external void free_owned_string(OwnedString self);

@ffi.Native<
  CResult_SecretSharesRes Function(
    ffi.Pointer<MultisigConfigWithName>,
    ffi.Uint8,
    StringView,
    ffi.Pointer<SecretShareMachineWrapper>,
    ffi.Pointer<StringView>,
    ffi.UintPtr,
  )
>()
external CResult_SecretSharesRes get_secret_shares(
  ffi.Pointer<MultisigConfigWithName> config,
  int language,
  StringView seed,
  ffi.Pointer<SecretShareMachineWrapper> machine,
  ffi.Pointer<StringView> commitments,
  int commitments_len,
);

@ffi.Native<ffi.Uint16 Function(ffi.Pointer<ThresholdKeysWrapper>)>()
external int keys_index(ffi.Pointer<ThresholdKeysWrapper> keys);

@ffi.Native<ffi.Uint16 Function(ffi.Pointer<ThresholdKeysWrapper>)>()
external int keys_participants(ffi.Pointer<ThresholdKeysWrapper> keys);

@ffi.Native<ffi.Uint16 Function(ffi.Pointer<ThresholdKeysWrapper>)>()
external int keys_threshold(ffi.Pointer<ThresholdKeysWrapper> keys);

@ffi.Native<
  ffi.Pointer<MultisigConfig> Function(ffi.Pointer<MultisigConfigWithName>)
>()
external ffi.Pointer<MultisigConfig> multisig_config(
  ffi.Pointer<MultisigConfigWithName> self,
);

@ffi.Native<StringView Function(ffi.Pointer<MultisigConfigWithName>)>()
external StringView multisig_my_name(ffi.Pointer<MultisigConfigWithName> self);

@ffi.Native<StringView Function(ffi.Pointer<MultisigConfig>)>()
external StringView multisig_name(ffi.Pointer<MultisigConfig> self);

@ffi.Native<StringView Function(ffi.Pointer<MultisigConfig>, ffi.UintPtr)>()
external StringView multisig_participant(
  ffi.Pointer<MultisigConfig> self,
  int i,
);

@ffi.Native<ffi.UintPtr Function(ffi.Pointer<MultisigConfig>)>()
external int multisig_participants(ffi.Pointer<MultisigConfig> self);

@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.Pointer<MultisigConfig>)>()
external ffi.Pointer<ffi.Uint8> multisig_salt(ffi.Pointer<MultisigConfig> self);

@ffi.Native<ffi.Uint16 Function(ffi.Pointer<MultisigConfig>)>()
external int multisig_threshold(ffi.Pointer<MultisigConfig> self);

@ffi.Native<
  CResult_MultisigConfigRes Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.UintPtr,
    ffi.Uint16,
    ffi.Pointer<StringView>,
    ffi.Uint16,
  )
>()
external CResult_MultisigConfigRes new_multisig_config(
  ffi.Pointer<ffi.Uint8> multisig_name$1,
  int multisig_name_len,
  int threshold,
  ffi.Pointer<StringView> participants,
  int participants_len,
);

@ffi.Native<
  CResult_ResharerConfigRes Function(
    ffi.Uint16,
    ffi.Pointer<ffi.Uint16>,
    ffi.Uint16,
    ffi.Pointer<StringView>,
    ffi.Uint16,
  )
>()
external CResult_ResharerConfigRes new_resharer_config(
  int new_threshold,
  ffi.Pointer<ffi.Uint16> resharers,
  int resharers_len,
  ffi.Pointer<StringView> new_participants,
  int new_participants_len,
);

@ffi.Native<
  CResult_SignConfigRes Function(
    ffi.Pointer<ThresholdKeysWrapper>,
    ffi.UnsignedInt,
    ffi.Pointer<PortableOutput>,
    ffi.UintPtr,
    ffi.UintPtr,
    ffi.Pointer<StringView>,
    ffi.Pointer<ffi.Uint64>,
    StringView,
    ffi.Uint64,
  )
>()
external CResult_SignConfigRes new_sign_config(
  ffi.Pointer<ThresholdKeysWrapper> keys,
  int network,
  ffi.Pointer<PortableOutput> outputs,
  int outputs_len,
  int payments,
  ffi.Pointer<StringView> payment_addresses,
  ffi.Pointer<ffi.Uint64> payment_amounts,
  StringView change,
  int fee_per_weight,
);

@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.Pointer<OwnedPortableOutput>)>()
external ffi.Pointer<ffi.Uint8> output_hash(
  ffi.Pointer<OwnedPortableOutput> self,
);

@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.Pointer<OwnedPortableOutput>)>()
external ffi.Pointer<ffi.Uint8> output_script_pubkey(
  ffi.Pointer<OwnedPortableOutput> self,
);

@ffi.Native<ffi.UintPtr Function(ffi.Pointer<OwnedPortableOutput>)>()
external int output_script_pubkey_len(ffi.Pointer<OwnedPortableOutput> self);

@ffi.Native<ffi.Uint64 Function(ffi.Pointer<OwnedPortableOutput>)>()
external int output_value(ffi.Pointer<OwnedPortableOutput> self);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<OwnedPortableOutput>)>()
external int output_vout(ffi.Pointer<OwnedPortableOutput> self);

@ffi.Native<StringView Function(ffi.Pointer<ResharerConfig>, ffi.UintPtr)>()
external StringView resharer_new_participant(
  ffi.Pointer<ResharerConfig> self,
  int i,
);

@ffi.Native<ffi.UintPtr Function(ffi.Pointer<ResharerConfig>)>()
external int resharer_new_participants(ffi.Pointer<ResharerConfig> self);

@ffi.Native<ffi.Uint16 Function(ffi.Pointer<ResharerConfig>)>()
external int resharer_new_threshold(ffi.Pointer<ResharerConfig> self);

@ffi.Native<ffi.Uint16 Function(ffi.Pointer<ResharerConfig>, ffi.UintPtr)>()
external int resharer_resharer(ffi.Pointer<ResharerConfig> self, int i);

@ffi.Native<ffi.UintPtr Function(ffi.Pointer<ResharerConfig>)>()
external int resharer_resharers(ffi.Pointer<ResharerConfig> self);

@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.Pointer<ResharerConfig>)>()
external ffi.Pointer<ffi.Uint8> resharer_salt(ffi.Pointer<ResharerConfig> self);

@ffi.Native<
  CResult_OwnedString Function(
    ffi.Pointer<ThresholdKeysWrapper>,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Bool,
    ffi.Bool,
  )
>()
external CResult_OwnedString script_pubkey_for_keys(
  ffi.Pointer<ThresholdKeysWrapper> keys,
  int account,
  int address,
  bool change,
  bool secure,
);

@ffi.Native<OwnedString Function(ffi.Pointer<ThresholdKeysWrapper>)>()
external OwnedString serialize_keys(ffi.Pointer<ThresholdKeysWrapper> keys);

@ffi.Native<StringView Function(ffi.Pointer<SignConfig>)>()
external StringView sign_change(ffi.Pointer<SignConfig> self);

@ffi.Native<ffi.Uint64 Function(ffi.Pointer<SignConfig>)>()
external int sign_fee_per_weight(ffi.Pointer<SignConfig> self);

@ffi.Native<
  ffi.Pointer<OwnedPortableOutput> Function(
    ffi.Pointer<SignConfig>,
    ffi.UintPtr,
  )
>()
external ffi.Pointer<OwnedPortableOutput> sign_input(
  ffi.Pointer<SignConfig> self,
  int i,
);

@ffi.Native<ffi.UintPtr Function(ffi.Pointer<SignConfig>)>()
external int sign_inputs(ffi.Pointer<SignConfig> self);

@ffi.Native<StringView Function(ffi.Pointer<SignConfig>, ffi.UintPtr)>()
external StringView sign_payment_address(ffi.Pointer<SignConfig> self, int i);

@ffi.Native<ffi.Uint64 Function(ffi.Pointer<SignConfig>, ffi.UintPtr)>()
external int sign_payment_amount(ffi.Pointer<SignConfig> self, int i);

@ffi.Native<ffi.UintPtr Function(ffi.Pointer<SignConfig>)>()
external int sign_payments(ffi.Pointer<SignConfig> self);

@ffi.Native<
  CResult_StartKeyGenRes Function(
    ffi.Pointer<MultisigConfig>,
    StringView,
    ffi.Uint8,
  )
>()
external CResult_StartKeyGenRes start_key_gen(
  ffi.Pointer<MultisigConfig> config,
  StringView my_name,
  int language,
);

@ffi.Native<
  CResult_StartResharedRes Function(
    StringView,
    ffi.Pointer<ResharerConfig>,
    StringView,
    ffi.Pointer<StringView>,
  )
>()
external CResult_StartResharedRes start_reshared(
  StringView multisig_name$1,
  ffi.Pointer<ResharerConfig> resharer_config,
  StringView my_name,
  ffi.Pointer<StringView> resharer_starts,
);

@ffi.Native<
  CResult_StartResharerRes Function(
    ffi.Pointer<ThresholdKeysWrapper>,
    ffi.Pointer<ResharerConfig>,
  )
>()
external CResult_StartResharerRes start_resharer(
  ffi.Pointer<ThresholdKeysWrapper> keys,
  ffi.Pointer<ResharerConfig> config,
);

final class AttemptSignRes extends ffi.Struct {
  external ffi.Pointer<TransactionSignMachineWrapper> machine;

  external OwnedString preprocess;
}

final class CResult_AttemptSignRes extends ffi.Struct {
  external ffi.Pointer<AttemptSignRes> value;

  @ffi.Uint8()
  external int err;

  static ffi.Pointer<CResult_AttemptSignRes> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<AttemptSignRes> value,
    required int err,
  }) => $allocator<CResult_AttemptSignRes>()
    ..ref.value = value
    ..ref.err = err;
}

final class CResult_ContinueSignRes extends ffi.Struct {
  external ffi.Pointer<ContinueSignRes> value;

  @ffi.Uint8()
  external int err;

  static ffi.Pointer<CResult_ContinueSignRes> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ContinueSignRes> value,
    required int err,
  }) => $allocator<CResult_ContinueSignRes>()
    ..ref.value = value
    ..ref.err = err;
}

final class CResult_KeyGenRes extends ffi.Struct {
  external ffi.Pointer<KeyGenRes> value;

  @ffi.Uint8()
  external int err;

  static ffi.Pointer<CResult_KeyGenRes> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<KeyGenRes> value,
    required int err,
  }) => $allocator<CResult_KeyGenRes>()
    ..ref.value = value
    ..ref.err = err;
}

final class CResult_MultisigConfig extends ffi.Struct {
  external ffi.Pointer<MultisigConfig> value;

  @ffi.Uint8()
  external int err;

  static ffi.Pointer<CResult_MultisigConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<MultisigConfig> value,
    required int err,
  }) => $allocator<CResult_MultisigConfig>()
    ..ref.value = value
    ..ref.err = err;
}

final class CResult_MultisigConfigRes extends ffi.Struct {
  external ffi.Pointer<MultisigConfigRes> value;

  @ffi.Uint8()
  external int err;

  static ffi.Pointer<CResult_MultisigConfigRes> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<MultisigConfigRes> value,
    required int err,
  }) => $allocator<CResult_MultisigConfigRes>()
    ..ref.value = value
    ..ref.err = err;
}

final class CResult_OwnedString extends ffi.Struct {
  external ffi.Pointer<OwnedString> value;

  @ffi.Uint8()
  external int err;

  static ffi.Pointer<CResult_OwnedString> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<OwnedString> value,
    required int err,
  }) => $allocator<CResult_OwnedString>()
    ..ref.value = value
    ..ref.err = err;
}

final class CResult_ResharedRes extends ffi.Struct {
  external ffi.Pointer<ResharedRes> value;

  @ffi.Uint8()
  external int err;

  static ffi.Pointer<CResult_ResharedRes> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ResharedRes> value,
    required int err,
  }) => $allocator<CResult_ResharedRes>()
    ..ref.value = value
    ..ref.err = err;
}

final class CResult_ResharerConfig extends ffi.Struct {
  external ffi.Pointer<ResharerConfig> value;

  @ffi.Uint8()
  external int err;

  static ffi.Pointer<CResult_ResharerConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ResharerConfig> value,
    required int err,
  }) => $allocator<CResult_ResharerConfig>()
    ..ref.value = value
    ..ref.err = err;
}

final class CResult_ResharerConfigRes extends ffi.Struct {
  external ffi.Pointer<ResharerConfigRes> value;

  @ffi.Uint8()
  external int err;

  static ffi.Pointer<CResult_ResharerConfigRes> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ResharerConfigRes> value,
    required int err,
  }) => $allocator<CResult_ResharerConfigRes>()
    ..ref.value = value
    ..ref.err = err;
}

final class CResult_SecretSharesRes extends ffi.Struct {
  external ffi.Pointer<SecretSharesRes> value;

  @ffi.Uint8()
  external int err;

  static ffi.Pointer<CResult_SecretSharesRes> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<SecretSharesRes> value,
    required int err,
  }) => $allocator<CResult_SecretSharesRes>()
    ..ref.value = value
    ..ref.err = err;
}

final class CResult_SignConfig extends ffi.Struct {
  external ffi.Pointer<SignConfig> value;

  @ffi.Uint8()
  external int err;

  static ffi.Pointer<CResult_SignConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<SignConfig> value,
    required int err,
  }) => $allocator<CResult_SignConfig>()
    ..ref.value = value
    ..ref.err = err;
}

final class CResult_SignConfigRes extends ffi.Struct {
  external ffi.Pointer<SignConfigRes> value;

  @ffi.Uint8()
  external int err;

  static ffi.Pointer<CResult_SignConfigRes> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<SignConfigRes> value,
    required int err,
  }) => $allocator<CResult_SignConfigRes>()
    ..ref.value = value
    ..ref.err = err;
}

final class CResult_StartKeyGenRes extends ffi.Struct {
  external ffi.Pointer<StartKeyGenRes> value;

  @ffi.Uint8()
  external int err;

  static ffi.Pointer<CResult_StartKeyGenRes> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<StartKeyGenRes> value,
    required int err,
  }) => $allocator<CResult_StartKeyGenRes>()
    ..ref.value = value
    ..ref.err = err;
}

final class CResult_StartResharedRes extends ffi.Struct {
  external ffi.Pointer<StartResharedRes> value;

  @ffi.Uint8()
  external int err;

  static ffi.Pointer<CResult_StartResharedRes> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<StartResharedRes> value,
    required int err,
  }) => $allocator<CResult_StartResharedRes>()
    ..ref.value = value
    ..ref.err = err;
}

final class CResult_StartResharerRes extends ffi.Struct {
  external ffi.Pointer<StartResharerRes> value;

  @ffi.Uint8()
  external int err;

  static ffi.Pointer<CResult_StartResharerRes> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<StartResharerRes> value,
    required int err,
  }) => $allocator<CResult_StartResharerRes>()
    ..ref.value = value
    ..ref.err = err;
}

final class CResult_ThresholdKeysWrapper extends ffi.Struct {
  external ffi.Pointer<ThresholdKeysWrapper> value;

  @ffi.Uint8()
  external int err;

  static ffi.Pointer<CResult_ThresholdKeysWrapper> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ThresholdKeysWrapper> value,
    required int err,
  }) => $allocator<CResult_ThresholdKeysWrapper>()
    ..ref.value = value
    ..ref.err = err;
}

final class ContinueSignRes extends ffi.Struct {
  external ffi.Pointer<TransactionSignatureMachineWrapper> machine;

  external OwnedString preprocess;
}

const int DUPLICATED_PARTICIPANT_ERROR = 82;

const int DUST_ERROR = 66;

const int FEE_ERROR = 71;

const int INVALID_ADDRESS_ERROR = 62;

const int INVALID_AMOUNT_OF_COMMITMENTS_ERROR = 46;

const int INVALID_AMOUNT_OF_SHARES_ERROR = 48;

const int INVALID_COMMITMENTS_ERROR = 47;

const int INVALID_DERIVATION_ERROR = 72;

const int INVALID_ENCODING_ERROR = 22;

const int INVALID_NAME_ERROR = 43;

const int INVALID_NETWORK_ERROR = 63;

const int INVALID_OUTPUT_ERROR = 61;

const int INVALID_PARTICIPANTS_AMOUNT_ERROR = 81;

const int INVALID_PARTICIPANT_ERROR = 23;

const int INVALID_PREPROCESS_ERROR = 70;

const int INVALID_RESHARED_MSG_ERROR = 84;

const int INVALID_RESHARER_MSG_ERROR = 85;

const int INVALID_SEED_ERROR = 45;

const int INVALID_SHARE_ERROR = 24;

const int INVALID_THRESHOLD_ERROR = 42;

final class KeyGenRes extends ffi.Struct {
  @ffi.Array.multi([32])
  external ffi.Array<ffi.Uint8> multisig_id;

  external ffi.Pointer<ThresholdKeysWrapper> keys;

  external OwnedString recovery;
}

final class KeyMachineWrapper extends ffi.Opaque {}

const int LANGUAGE_CHINESE_SIMPLIFIED = 2;

const int LANGUAGE_CHINESE_TRADITIONAL = 3;

const int LANGUAGE_ENGLISH = 1;

const int LANGUAGE_FRENCH = 4;

const int LANGUAGE_ITALIAN = 5;

const int LANGUAGE_JAPANESE = 6;

const int LANGUAGE_KOREAN = 7;

const int LANGUAGE_SPANISH = 8;

final class MultisigConfig extends ffi.Opaque {}

final class MultisigConfigRes extends ffi.Struct {
  external ffi.Pointer<MultisigConfig> config;

  external OwnedString encoded;
}

final class MultisigConfigWithName extends ffi.Struct {
  external ffi.Pointer<MultisigConfig> config;

  external ffi.Pointer<RustString> my_name;

  static ffi.Pointer<MultisigConfigWithName> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<MultisigConfig> config,
    required ffi.Pointer<RustString> my_name,
  }) => $allocator<MultisigConfigWithName>()
    ..ref.config = config
    ..ref.my_name = my_name;
}

const int NOT_ENOUGH_FUNDS_ERROR = 67;

const int NOT_ENOUGH_RESHARERS_ERROR = 83;

const int NO_INPUTS_ERROR = 64;

const int NO_OUTPUTS_ERROR = 65;

sealed class Network {
  static const Mainnet = 0;
  static const Testnet = 1;
  static const Regtest = 2;
}

final class OpaqueResharedMachine extends ffi.Opaque {}

final class OpaqueResharingMachine extends ffi.Opaque {}

final class OwnedPortableOutput extends ffi.Opaque {}

final class OwnedString extends ffi.Struct {
  external ffi.Pointer<RustString> str_box;

  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.UintPtr()
  external int len;

  static ffi.Pointer<OwnedString> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<RustString> str_box,
    required ffi.Pointer<ffi.Uint8> ptr,
    required int len,
  }) => $allocator<OwnedString>()
    ..ref.str_box = str_box
    ..ref.ptr = ptr
    ..ref.len = len;
}

final class PortableOutput extends ffi.Struct {
  @ffi.Array.multi([32])
  external ffi.Array<ffi.Uint8> hash;

  @ffi.Uint32()
  external int vout;

  @ffi.Uint64()
  external int value;

  external ffi.Pointer<ffi.Uint8> script_pubkey;

  @ffi.UintPtr()
  external int script_pubkey_len;

  @ffi.Uint32()
  external int account;

  @ffi.Uint32()
  external int address;

  @ffi.Bool()
  external bool change;

  @ffi.Bool()
  external bool secure;
}

final class ResharedRes extends ffi.Struct {
  external ffi.Pointer<MultisigConfig> config;

  external OwnedString id;

  external ffi.Pointer<ThresholdKeysWrapper> keys;
}

final class ResharerConfig extends ffi.Opaque {}

final class ResharerConfigRes extends ffi.Struct {
  external ffi.Pointer<ResharerConfig> config;

  external OwnedString encoded;
}

final class RustString extends ffi.Opaque {}

final class SecretShareMachineWrapper extends ffi.Opaque {}

final class SecretSharesRes extends ffi.Struct {
  external ffi.Pointer<KeyMachineWrapper> machine;

  external ffi.Pointer<Vec_u8> internal_commitments;

  external OwnedString shares;
}

final class SignConfig extends ffi.Opaque {}

final class SignConfigRes extends ffi.Struct {
  external ffi.Pointer<SignConfig> config;

  external OwnedString encoded;
}

final class StartKeyGenRes extends ffi.Struct {
  external OwnedString seed;

  external ffi.Pointer<MultisigConfigWithName> config;

  external ffi.Pointer<SecretShareMachineWrapper> machine;

  external OwnedString commitments;
}

final class StartResharedRes extends ffi.Struct {
  @ffi.UintPtr()
  external int resharers_len;

  external ffi.Pointer<MultisigConfig> multisig_config$1;

  @ffi.Uint16()
  external int my_i;

  external ffi.Pointer<OpaqueResharedMachine> machine;

  external OwnedString encoded;
}

final class StartResharerRes extends ffi.Struct {
  @ffi.UintPtr()
  external int new_participants_len;

  external ffi.Pointer<OpaqueResharingMachine> machine;

  external OwnedString encoded;
}

final class StringView extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.UintPtr()
  external int len;

  static ffi.Pointer<StringView> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Uint8> ptr,
    required int len,
  }) => $allocator<StringView>()
    ..ref.ptr = ptr
    ..ref.len = len;
}

const int TOO_LARGE_TRANSACTION_ERROR = 68;

final class ThresholdKeysWrapper extends ffi.Opaque {}

final class TransactionSignMachineWrapper extends ffi.Opaque {}

final class TransactionSignatureMachineWrapper extends ffi.Opaque {}

const int UNKNOWN_ERROR = 21;

const int UNKNOWN_LANGUAGE_ERROR = 44;

final class Vec_u8 extends ffi.Opaque {}

const int WRONG_KEYS_ERROR = 69;

const int ZERO_PARAMETER_ERROR = 41;
